driver.get("https://degoo.com/")
        driver.find_element_by_id("Email").click()
        driver.find_element_by_id("Email").clear()
        driver.find_element_by_id("Email").send_keys("bodhamkk@gmail.com")
        driver.find_element_by_id("Password").click()
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("suuuuuuuuuu1SX")
        driver.find_element_by_id("submit-btn-ff734fd2-dd44-4b79-a7ac-2409605aecf3").click()
        driver.find_element_by_link_text("Choose this plan").click()
